// Copyright © Bedrockbreaker 2025. MIT License

#pragma once

#include "Abilities/GameplayAbilityTargetTypes.h"

#include "GSpellContext.generated.h"

/** Context for a spell. Generated by UGSpellDelivery subclasses, consumed by UGSpellEffects. */
USTRUCT(BlueprintType)
struct FGSpellContext : public FGameplayAbilityTargetData
{
	GENERATED_BODY()

public:
	UPROPERTY(BlueprintReadWrite, Category = "Spell System|Context")
	TArray<TWeakObjectPtr<AActor>> TargetActors;

	UPROPERTY(BlueprintReadWrite, Category = "Spell System|Context")
	FVector TargetLocation = FVector::ZeroVector;

	UPROPERTY(BlueprintReadWrite, Category = "Spell System|Context")
	TMap<FGameplayTag, float> ExtraData;

	virtual UScriptStruct* GetScriptStruct() const override { return StaticStruct(); }

	virtual FString ToString() const override
	{
		return FString::Printf(
			TEXT("FSpellContext: %d Targets, Location: %s, %d Extra Data tags"),
			TargetActors.Num(),
			*TargetLocation.ToString(),
			ExtraData.Num());
	}
};
